### ISSUE TITLE
Group and rename unit and integration tests to be aligned with our charm repos and to be operated via terraform

### ISSUE THREAD

**Issue by merkata** [canonical/operator-workflows#181]
Our repos include two checks that are required to pass on PRs, where `operator-workflows` drifts from that and has a single check:

```text
      ~ required_status_checks {
          ~ contexts = [
              - "check",
              + "integration-tests / Required Integration Test Status Checks",
              + "unit-tests / Required Test Status Checks",
            ]
```

The tests need to be grouped, so that this repo conforms to the structure of our charm repos and so that terraform can maintain that state.

**Comment by arturo-seijas** [comment]
This is already supported by automation. I'm closing this ticket
