### ISSUE TITLE
Support repos without charmcraft.yaml

### ISSUE THREAD

**Issue by jdkandersson** [canonical/operator-workflows#26]
Thanks for creating these! I was going to use the test workflow for the charm documentation repo (https://github.com/canonical/upload-charm-docs). I encountered an error where, since that repo does not define a charm, there is no `charmcraft.yaml` file to figure out which Ubuntu version to use. Could this kind of repo be supported as well? For now, I just added that file and it seems to work fine.

Additionally, maybe for another issue, is there a way to support integration tests that don't need any images? Currently the workflow just stops in that case.

**Comment by arturo-seijas** [comment]
Integration tests are running when no images are present. You can find a more detailed explanation [here](https://github.com/canonical/upload-charm-docs/pull/3#discussion_r1017686872)
