### ISSUE TITLE
upload-artifact has a race condition

### ISSUE THREAD

**Issue by mthaddon** [canonical/operator-workflows#266]
Currently upload-artifact (v4) has a race condition. Per https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new:
"""
The contents of an Artifact are uploaded together into an immutable archive. They cannot be altered by subsequent jobs unless the Artifacts are deleted and recreated (where they will have a new ID).
"""
However, if you have multiple jobs running at the same time they will all delete the artifact and then try to upload and potentially fail. We saw this on the jenkins-k8s-operator worfklow. Two out of three failed, because they were all trying to upload at exactly "Thu, 21 Mar 2024 10:18:28 GMT".

We should consider adding a retry.

**Comment by amandahla** [comment]
@weiiwang01 is this issue still relevant?

**Comment by weiiwang01** [comment]
> @weiiwang01 is this issue still relevant?

This has been resolved in the newer version of the `operator-workflows`, close this issue, thanks!
