### ISSUE TITLE
Check inclusion of expected commands

### ISSUE THREAD

**Issue by jdkandersson** [canonical/operator-workflows#39]
The operator workflows are great, they reduce the maintenance burden for our GitHub actions! Currently we just look for the inclusions of certain tox commands, should we also check whether the tox actions run all the required checks? E.g., that linting actually runs all of the tools we expect to be run?

**Comment by arturo-seijas** [comment]
@jdkandersson , Iirc, this has already been implemented. Should we close this ticket?
