### ISSUE TITLE
promote-charm: doc-automation-disabled unexpectedly requires Discourse creds

### ISSUE THREAD

**Issue by andrei-polukhin** [canonical/operator-workflows#400]
Dear team!

I am using the `promote_charm.yaml` GitHub workflow, but I have a weird experience using the `doc-automation-disabled: true` parameter. My expectation is that the `Publish docs` step is fully skipped, but it doesn't appear to be the case:

https://github.com/canonical/operator-workflows/blob/34f1737e6cc607279375ffe357c63b5444793c8e/.github/workflows/promote_charm.yaml#L200-L201

Instead, this input is thrown into the `dry_run` parameter, which looks a bit weird to me:

https://github.com/canonical/operator-workflows/blob/34f1737e6cc607279375ffe357c63b5444793c8e/.github/workflows/promote_charm.yaml#L220

The problem with this approach is that I do not want any documentation to be published, which is clearly shown as the `description` to my parameter, but when running with the documentation disabled and w/o Discourse credentials, I get the following error in the GitHub workflow:
```shell
INFO:root:Base branch: main (commit e01531f185ba35cc35fbce909436923d6e69fc0c)
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 257, in <module>
    main()
  File "/usr/src/app/main.py", line 240, in main
    assert main_checks(user_inputs=user_inputs)  # pylint: disable=no-value-for-parameter
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/main.py", line 170, in wrapper
    output = func(execute_cwd, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/main.py", line 224, in main_checks
    clients = get_clients(user_inputs, path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/src/clients.py", line 38, in get_clients
    discourse=create_discourse(
              ^^^^^^^^^^^^^^^^^
  File "/usr/src/app/src/discourse.py", line 541, in create_discourse
    raise InputError(
src.exceptions.InputError: Invalid 'discourse_api_username' input, it must be non-empty, got api_username=''
```

Could we change the `if` condition for the `Publish docs` step so that it does not run on `doc-automation-disabled: true`? Here is my GitHub workflow file for posterity: https://github.com/canonical/pro-airgapped/blob/e01531f185ba35cc35fbce909436923d6e69fc0c/.github/workflows/charm-promotion.yml

Thank you very much in advance!

**Comment by cbartz** [comment]
Hi, thanks for bringing this up. This is not an easy decision to make, as I think we (Platform Engineering) might still want to use the `dry_run` parameter to see what would happen if we actually tried to publish the docs before eventually setting `doc-aumtation-disabled` to true. We'll discuss this internally. Thank you very much.
