### ISSUE TITLE
Enable `security.nesting` for `rockcraft pack`

### ISSUE THREAD

**Issue by kelkawi-a** [canonical/operator-workflows#441]
Reference: https://github.com/canonical/craft-providers/issues/591

We have a rock to be built which spins up a docker container as part of the build process to generate some database queries and metadata. Such functionality is not enabled by default in `rockcraft`. After some digging around, it seems that setting `lxc --project=rockcraft profile set default security.nesting true` on the lxc container before running `rockcraft pack` allows this to be done. Would it be possible to add this setting as a parameter to the integration tests?

**Comment by cbartz** [comment]
Seems this is now implemented by #443 .
