### ISSUE TITLE
planBuildFileResource doesn't support optional file resources

### ISSUE THREAD

**Issue by nrobinaubertin** [canonical/operator-workflows#489]
[bind-operator](https://github.com/canonical/bind-operator) is [declaring a file resource](https://github.com/canonical/bind-operator/blob/main/metadata.yaml#L35) in its metadata but it is [entirely optional](https://github.com/canonical/bind-operator/blob/main/src/charm.py#L69) and mostly there for debugging purposes.  

Since https://github.com/canonical/operator-workflows/pull/454, I can't pass integration tests anymore because operator-workflow [is asking me to provide a script](https://github.com/canonical/bind-operator/actions/runs/12071425977/job/33663167389?pr=56#step:5:20) to build this resource. That doesn't really make sense in my case, the snap file is handled in a [different repository](https://github.com/canonical/charmed-bind/).  

Is there a way to opt out of this behavior ?

**Comment by javierdelapuente** [comment]
@weiiwang01 can you have a look at this issue? Thanks!

**Comment by weiiwang01** [comment]
Is this debugging file resource used often? If not, maybe remove this resource definition from `charmcraft.yaml` and adding it back locally when needed? This has the additional benefit of ensuring the charmhub version will not have the resource defined.

**Comment by weiiwang01** [comment]
I am not entirely sure if a resource can be defined but not uploaded on Charmhub. It definitely can be now, but I am not sure if this is by design.  

How about adding a marker to the resources? For example, we could prefix the description with `(local)` and skip the resource in the workflows. What do you think?

**Comment by nrobinaubertin** [comment]
Yes, that's a good workaround idea (it would work for me at least). So instead of `description: charmed-bind snap file for debugging purposes`, I would write `description: (local) charmed-bind snap file for debugging purposes` ?

**Comment by weiiwang01** [comment]
Pull request created: https://github.com/canonical/operator-workflows/pull/493
