### ISSUE TITLE
Craft tools get executed with an empty `$PATH`

### ISSUE THREAD

**Issue by lengau** [canonical/operator-workflows#496]
When [running craft tools](https://github.com/canonical/operator-workflows/blob/27022a81469d5c31da80f2e5fa26e7fa2bdb260f/src/build.ts#L107-L110), the environment gets replaced rather than updated, so snapd gets an [empty `$PATH`](https://bugs.launchpad.net/snapd/+bug/2090938).

This causes Charmcraft to think the cache directory is `/cache` because snapd sets `SNAP_USER_COMMON` to an empty value, which causes charmcraft to fail when trying to create the cache directory.

**Comment by yanksyoon** [comment]
Operator workflows side has been fixed by: https://github.com/canonical/operator-workflows/pull/497.
Closing :)
