### ISSUE TITLE
Check lint and test stdout step should report all missing dependencies in one pass

### ISSUE THREAD

**Issue by merkata** [canonical/operator-workflows#77]
Currently, the `Check lint and test stdout` step checks for missing linting dependencies in the `tox.ini` file and exits as soon as one is not available. If more dependencies are missing, you would get a new error on every consecutive run. It is better to gather all missing dependencies and present this as an output and then fail, permitting the user to fix all missing deps at one pass.

**Comment by jdkandersson** [comment]
This would be great! Another change that could be good to include is to actually base the required linters on content on the https://github.com/canonical/is-charms-contributing-guide repo

**Comment by jdkandersson** [comment]
As a workaround, this file can be check for which linters are required: https://github.com/canonical/operator-workflows/blob/main/tests/workflows/test/simple/tox.ini

**Comment by jdkandersson** [comment]
The benefits of having tests 😉

**Comment by merkata** [comment]
> The benefits of having tests wink

Exactly, it naturally gets you into a more structured way of reasoning and improving, I like it :)

**Comment by amandahla** [comment]
@jdkandersson is this issue still relevant?
